spring:
  application:
    name: AcpCsw1

  datasource:
    url: ${acp.postgres}
    username: "${POSTGRES_USER:postgres}"
    password: "${POSTGRES_PASSWORD:postgres}"
    driver-class-name: org.postgresql.Driver



info:
  app:
    name: AcpCsw1
    description: This is the ACP Coursework 1 Rest Service
    version: 1.0

management:
  endpoints:
    web:
      exposure:
        include: info, health, env
  info:
    env:
      enabled: true

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true


logging:
  level:
    web: debug

springdoc:
  api-docs:
    enabled: true

server:
  port: 8080


acp:
  postgres: "${ACP_POSTGRES:jdbc:postgresql://localhost:5432/acp}"
  s3: "${ACP_S3:http://localhost:4566}"
  dynamodb: "${ACP_DYNAMODB:http://localhost:4566}"
  ilp: "${ACP_URL_ENDPOINT:${ACP_ILP_ENDPOINT:https://ilp-rest-2025-bvh6e9hschfagrgy.ukwest-01.azurewebsites.net}}"
  sid: "${ACP_SID:s2274790}"

