spring:
  application:
    name: AcpCsw1

info:
  app:
    name: AcpCsw1
    description: This is the ACP Coursework 1 Rest Service
    version: 1.0

management:
  endpoints:
    web:
      exposure:
        include: info, health, env
  info:
    env:
      enabled: true

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true


logging:
  level:
    web: debug

springdoc:
  api-docs:
    enabled: true

server:
  port: 8080


acp:
  postgres: ${ACP_POSTGRES}
  s3: ${ACP_S3}
  dynamodb: ${ACP_DYNAMODB}
  # ilp-endpoint: https://ilp-rest-2025-all-assigned.azurewebsites.net/ABC
